name: AI Image Upscaler

on:
  push:
    paths:
      - 'input.rar'

jobs:
  upscale:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install unrar
        pip install -r requirements.txt
    
    - name: Run upscaler
      env: 
          RAR_PASSWORD: ${{ secrets.RAR_PASSWORD }}
      run: python upscaler.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: upscaled-images
        path: upscaled_images.zip
