name: Image Upscaler

on:
  push:
    paths:
      - 'input.zip'

jobs:
  upscale:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow torch super-image
    
    - name: Run upscaler
      run: python upscaler.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: upscaled-images
        path: upscaled_images.zip
